version: "3.9"
services:
  dns:
    build: ./dns
    environment:
      - PORT=10053
  old-service:
    build: ./srv
    command: ["-t", "old"]
    environment:
      - PORT=10080
  new-service:
    build: ./srv
    command: ["-t", "new"]
    environment:
      - PORT=10080
  nginx.test:
    build: ./srv
    command: ["-t", "without resolver"]
    environment:
      - PORT=10080
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    command: ["nginx-debug", "-g", "daemon off;"]
    ports:
      - "8080:80"
